### ISSUE TITLE
Resource pack not working on Lunar Client (1.21 Java)

### ISSUE THREAD

**Issue by MoralMedusa** [emberjams/jellyjams#1]
I have downloaded the 1.21 compatible version, and placed the folder in my resource packs, however, when I turn it on in the resource packs section, it does nothing at all. I have even tried deleting and redownloading the pack. It continues to not do anything.

How can i fix this??

**Comment by emberjams** [comment]
I'm looking into the incompatability, but optifine based resourcepacks should work on that client.

**Comment by emberjams** [comment]
Didn't mean to close it oops!

**Comment by emberjams** [comment]
Ok so what I have found is that there are add-ons in the version selector for optifine/fabric on to Lunar Client that allows for optifine-based packs to work. This add-on(s) simply is/are not available yet on 1.21/1.21.1 All you have to do is wait until the add-on comes out to add any optifine resourcepack you would like.

**Comment by MoralMedusa** [comment]
> Ok so what I have found is that there are add-ons in the version selector for optifine/fabric on to Lunar Client that allows for optifine-based packs to work. This add-on(s) simply is/are not available yet on 1.21/1.21.1 All you have to do is wait until the add-on comes out to add any optifine resourcepack you would like.

Okay, so just give it some time and eventually it will work? cool, thank u so much.

**Comment by emberjams** [comment]
Yeah whenever Lunar updates its add-on services. Keep checking the launcher for it!
