### ISSUE TITLE
The Pigs texture do not show up

### ISSUE THREAD

**Issue by SweetPeaxches** [emberjams/jellyjams#2]
I'm using version 1.20.1 Fabric
The textures for the Pigs do not show up.
![2024-12-29 (5)](https://github.com/user-attachments/assets/1335ebae-a5d3-45df-a287-1d96279ec2ab)

Never Mind I figured it out, instead of using 1.20.1 i switched the recourse pack to the newer version

**Comment by ember-jams** [comment]
haha no problem
